apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-configmap
  namespace: evaluation-service
  labels:
    app: evaluation-service
data:
  REDIS_URL: "redis://clustercfg.evaluation-service-cache.nu6bxp.use1.cache.amazonaws.com:6379"
  FLAG_SERVICE_URL: "http://flag-service-clusterip.flag-service.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service-clusterip.targeting-service.svc.cluster.local:8003"
  SERVICE_API_KEY: "tm_key_84a97ca7cf27aae18e75422ce6ae73ded24c1c539bfada2bdec8e4535da437e7"
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/832200544765/analytics-service-sqs"
