apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: auth-service
  labels:
    app: auth-service
data:
  DATABASE_URL: postgres://postgres:t5VXvdq7Nu3eMpk@auth-service-db.c5eki0oao3n1.us-east-1.rds.amazonaws.com:5432/postgres