apiVersion: v1
kind: Secret
metadata:
  name: targeting-secret
  namespace: targeting-service
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: a2MzVk1HMWdYeDAx
  POSTGRES_DB: dGFyZ2V0aW5nLXNlcnZpY2UtZGI=