apiVersion: v1
kind: Secret
metadata:
  name: flag-secret
  namespace: flag-service
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: N0RoM2F2clNoODBh
  POSTGRES_DB: ZmxhZy1zZXJ2aWNlLWRi
